---
output: 
  pagedown::html_paged:
    css: www/styles_MIDN_pages.css
    toc: false
    numbered_sections: false
    number_sections: false
    includes:
      in_header: "header_manual.html"

params:
  park: 'FRSP' #'RICH' #'PETE'
  from: 2007
  from_4yr: 2021
  to: 2023
  QAQC: FALSE
  locType: 'VS'
  cycle_latest: 5
  from_prev: 2016
  to_prev: 2019
---
```{r echo = F}
htmltools::includeHTML("header_manual.html")
htmltools::includeHTML("footer.html")

```

```{r setup, include = FALSE, results = 'hide'}
knitr::opts_chunk$set(echo = FALSE)
options(knitr.kable.NA = '')

library(pagedown)
library(tidyverse)
library(forestMIDN)
library(htmltools)
library(knitr)
library(kableExtra)
library(cowplot)
#devtools::install_github(repo="haozhu233/kableExtra", ref="a6af5c0") # for collapse_rows()
library(kableExtra)
#devtools::install_github("katemmiller/forestTrends")
library(forestTrends)
library(sf)
library(vegan)
```

```{r cache = T, results = 'hide', include = F}
importData()
```

```{r}
park = params$park
from = as.numeric(params$from)
from_4yr = as.numeric(params$from_4yr)
to = as.numeric(params$to)
QAQC = params$QAQC
locType = params$locType
cycle_latest = as.numeric(params$cycle_latest)
from_prev = as.numeric(params$from_prev)
to_prev = as.numeric(params$to_prev)

# park = 'FRSP' #'RICH' #'PETE'
# from = 2007
# from_4yr = 2021
# to = 2023
# QAQC = FALSE
# locType = 'VS'
# cycle_latest = 5
# from_prev = 2016
# to_prev = 2019

```

```{r results = 'hide', include = F}
# Note that the stocking index calculated in both the summary code and regen debt code is on the 
# McWilliams 100 point scale, not the 1m2 scale that MIDN used to use.

# Imports/Libraries
library(forestMIDN)
library(forestTrends)
library(tidyverse)
library(sf)

#importData()

# Downgrade Fraxinus to subcanopy species
VIEWS_MIDN$Taxa_MIDN$IsCanopyExclusion[VIEWS_MIDN$Taxa_MIDN$Genus == "Fraxinus"] <- TRUE

# Params FRSP, RICH, PETE; from = 2007: from_4yr = 2021; cycle_latest = 5; from_prev = 2016; to_prev = 2019; 
# Params VAFO, HOFU, GETT, APCO, BOWA: from = 2007; from_4yr = 2019; cycle_latest = 4; from_prev = 2015; to_prev = 2018;
# Params GEWA, THST: from = 2008; from_4yr = 2021; cycle_latest = 4; from_prev = 2016; to_prev = 2019;
# Params COLO: from = 2011; from_4yr = 2019; cycle_latest = 3; from_prev = 2015; to_prev = 2018;
# Params SAHI: from = 2009; from_4yr = 2023; cycle_latest = 4; from_prev = 2017; to_prev = 2017;

park_crs = ifelse(park %in% c("APCO", "BOWA"), 26917, 26918)

num_plots = case_when(park == "APCO" ~ 28,
                      park == "ASIS" ~ 12, # Will be 24
                      park == "BOWA" ~ 8,
                      park == "COLO" ~ 48,
                      park == "FRSP" ~ 104,
                      park == "GETT" ~ 33,
                      park == "GEWA" ~ 8,
                      park == "HOFU" ~ 16,
                      park == "PETE" ~ 52,
                      park == "RICH" ~ 31,
                      park == "SAHI" ~ 4,
                      park == "THST" ~ 8,
                      park == "VAFO" ~ 28
                      )
plot_size = 400

args_all = list(park = park, from = from, to = to, QAQC = QAQC, locType = locType)
args_4yr = list(park = park, from = from_4yr, to = to, QAQC = QAQC, locType = locType)
args_vs = list(park = park, from = from, to = to, QAQC = QAQC, locType = "VS")

# Set up file structure
path = 'C:/NETN/Monitoring_Projects/Forest_Health/Data_Summaries/'

parks <- c("APCO", "ASIS", "BOWA", "COLO", "FRSP", "GETT", "GEWA", 
           "HOFU", "PETE", "RICH", "SAHI", "THST", "VAFO")

invisible(lapply(parks, function(x) {
  if(!dir.exists(paste0(path, x))){dir.create(paste0(path, x))}
})
)

new_path = paste0(path, park, "/", as.character(to), "/")

if(!dir.exists(new_path)){dir.create(new_path)}

folders <- c("GIS_projects", "figures", "map_exports", "shapefiles", "tables")

invisible(lapply(folders, function(x) {
  if(!dir.exists(paste0(new_path, x))){dir.create(paste0(new_path, x))}
})
)

# Read in tree species groups for regen and tree pie charts
trspp_grps <- read.csv("NPS_tree_species_groups.csv")
```
```{r results = 'hide', include = F}
# Source files
source('./scripts/forest_summary_code_MIDN.R')
```
```{r results = 'hide', include = F}
source('./scripts/regen_debt_metrics_MIDN.R')
```
```{r results = 'hide', include = F}
source('./scripts/tree_regen_stem_changes_by_species_loess_MIDN.R')
```

Forest Summary Report for: <span style="font-weight:bold;">`r params$park` `r params$year` </span>